management:
  endpoint:
    gateway:
      enabled: false
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 8080


spring:
  application:
    name: homi-gateway


homi:
  gateway:
    version: 0.0.4
  platform:
    url: ${HOMI_PLATFORM_API_URL}
    orgId: ${HOMI_ORG_ID}
    apiKey: ${HOMI_GATEWAY_KEY}

