management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 8080


spring:
  application:
    name: homi-gateway

  cloud:
    gateway:
      redis-route-definition-repository:
        enabled: false

  autoconfigure:
    exclude:  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration, \
              org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  redis:
    url: ${REDIS_URL}


homi:
  gatewayId: ${GATEWAY_ID:'default'}
  route:
    github:
      enabled: true
      token: ${GITHUB_TOKEN:'12346'}
      repo: homihq/gateway-route-config
      branch: master
      file: routes.yml



