management:
  endpoint:
    gateway:
      enabled: false
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 8080


spring:
  application:
    name: homi-gateway


homi:
  platform:
    url: ${HOMI_PLATFORM_API_URL}
  orgId: ${HOMI_ORG_ID}
  apiKey: ${HOMI_API_KEY_ID}

