management:
  .endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 8080


spring:
  cloud:
    gateway:
      redis-route-definition-repository:
        enabled: false
  application:
    name: homi-gateway

  redis:
    url: ${REDIS_URL}
